[package]
name = "chess-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = {path = "chess"}
#chess = "3.2.0"
arrayvec = "0.5.1"
nodrop = "0.1.14"
chrono = "0.4.20"
fasthash = "0.4.0"
